name: gymtracker_backend
description: GymTracker REST API backend.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.8.1
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  sqlite3: ^2.4.6
  uuid: ^4.5.2

dev_dependencies:
  lints: ^4.0.0
